# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow_list',
            field=models.ManyToManyField(blank=True, related_name='my_followers', to='app.UserProfile'),
        ),
    ]
