# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160907_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='pictures_link_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='weibo',
            name='video_link_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
