# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160907_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
